apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: slt3f8vqt-go
  janus-idp.io/tekton: slt3f8vqt-go
  backstage.io/kubernetes-id: slt3f8vqt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: slt3f8vqt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
