apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: slt3f8vqt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: slt3f8vqt-go 
  name: slt3f8vqt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: slt3f8vqt-go 
